name: nplet-build

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
    paths:
      - 'docker/nginx/**'
      - '.github/workflows/**'

env:
  PROJECT_NAME: nplet
  GHCR_REGISTRY: ghcr.io/zero88
  DOCKER_REGISTRY: docker.io/zero88

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.OSS_GITHUB_TOKEN }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          git-user-signingkey: true
          git-commit-gpgsign: true
          git-tag-gpgsign: true
          git-push-gpgsign: false
          gpg-private-key: ${{ secrets.CI_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.CI_GPG_PASSPHARSE }}

      - name: Project context
        id: context
        uses: zero88/gh-project-context@v1
        with:
          dry: false
          mustSign: true
          defaultBranch: master

      - name: Docker context
        id: docker_context
        run: |
          images=${{ env.GHCR_REGISTRY }}/${{ env.PROJECT_NAME }}
          [[ "${{ steps.context.outputs.isTag }}" == "true" ]] && images=$images,${{ env.DOCKER_REGISTRY }}/${{ env.PROJECT_NAME }}
          echo ::set-output name=argbashVersion::$(cat ./docker/nginx/argbash.txt)
          echo ::set-output name=images::$images

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ steps.docker_context.outputs.images }}
          tag-latest: true
          tag-sha: true
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        if: ${{ steps.context.outputs.decision_build == 'true' }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: ${{ steps.context.outputs.isTag == 'true' }}
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.OSS_GHA_DOCKER_HUB }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        if: ${{ steps.context.outputs.decision_build == 'true' }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.OSS_GITHUB_TOKEN }}

      - name: Docker build
        uses: docker/build-push-action@v2
        if: ${{ steps.context.outputs.decision_build == 'true' }}
        with:
          context: ./docker/nginx
          file: ./docker/nginx/Dockerfile
          build-args: |
            ARGBASH_VERSION=${{ steps.docker_context.outputs.argbashVersion }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          push: true

      - name: Copy artifact
        if: ${{ steps.context.outputs.isTag == 'true' }}
        run: |
          docker create --name ${{ env.PROJECT_NAME }} ${{ env.GHCR_REGISTRY }}/${{ env.PROJECT_NAME }}:${{ steps.context.outputs.version }}
          docker cp ${{ env.PROJECT_NAME }}:/app/${{ env.PROJECT_NAME }} /tmp/${{ env.PROJECT_NAME }}
          docker rm -f ${{ env.PROJECT_NAME }}

      - name: Create Release
        if: ${{ steps.context.outputs.isTag == 'true' }}
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.context.outputs.version }}
          name: Release v${{ steps.context.outputs.version }}
          draft: false
          prerelease: false
          files: /tmp/${{ env.PROJECT_NAME }}
